# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Doug Jordan
tagline:          'Personal musings'
description:      'Made by <a href="https://twitter.com/dwj300" target="_blank">@dwj300</a>.'
url:              https://blog.dougjordan.com
baseurl:          /

author:
  name:           'Douglas Jordan'
  url:            'https://dougjordan.com'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/dwj300/dwj300.github.io

gems:
- jekyll-paginate
- jekyll-gist
